version: '3'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - model_service

  model_service:
    build: ./model
    ports:
      - "5000:5000"

  redis:
    build: ./redis
    ports:
      - "6379:6379"